# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8870eb08bed0d8ee6a787eaa10853d3f93801ca333405393be9a4995b1a1270675a796fed42800e719b6a081d7a057b251d06e23be4c22d42dd5449187bdba4d

test:
  secret_key_base: 0d3f337c016ea7f220c9787e50ee5c542cc297014602bb12963a5171e6c8b0306c4f6a96d928e5a9248b8685b3546bb23d54c8139b7786be5b5b256379881300

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
